# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historical_map_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HistoricalMap(object):
    def setupUi(self, HistoricalMap):
        HistoricalMap.setObjectName(_fromUtf8("HistoricalMap"))
        HistoricalMap.resize(558, 533)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(74)
        sizePolicy.setVerticalStretch(74)
        sizePolicy.setHeightForWidth(HistoricalMap.sizePolicy().hasHeightForWidth())
        HistoricalMap.setSizePolicy(sizePolicy)
        HistoricalMap.setMinimumSize(QtCore.QSize(558, 480))
        HistoricalMap.setMaximumSize(QtCore.QSize(558, 533))
        self.label_15 = QtGui.QLabel(HistoricalMap)
        self.label_15.setGeometry(QtCore.QRect(9, 480, 161, 31))
        self.label_15.setMinimumSize(QtCore.QSize(161, 31))
        self.label_15.setMaximumSize(QtCore.QSize(161, 31))
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/ensat.gif")))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.tabWidget = QtGui.QTabWidget(HistoricalMap)
        self.tabWidget.setGeometry(QtCore.QRect(9, 113, 540, 362))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAccessibleDescription(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.inShapeMedianIter = gui.QgsSpinBox(self.tab)
        self.inShapeMedianIter.setGeometry(QtCore.QRect(386, 116, 80, 25))
        self.inShapeMedianIter.setMinimumSize(QtCore.QSize(70, 25))
        self.inShapeMedianIter.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.inShapeMedianIter.setFont(font)
        self.inShapeMedianIter.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.inShapeMedianIter.setMinimum(1)
        self.inShapeMedianIter.setMaximum(50)
        self.inShapeMedianIter.setSingleStep(1)
        self.inShapeMedianIter.setProperty("value", 5)
        self.inShapeMedianIter.setObjectName(_fromUtf8("inShapeMedianIter"))
        self.inShapeMedian = gui.QgsSpinBox(self.tab)
        self.inShapeMedian.setGeometry(QtCore.QRect(167, 116, 99, 25))
        self.inShapeMedian.setMinimumSize(QtCore.QSize(83, 25))
        self.inShapeMedian.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.inShapeMedian.setFont(font)
        self.inShapeMedian.setMinimum(1)
        self.inShapeMedian.setMaximum(31)
        self.inShapeMedian.setSingleStep(2)
        self.inShapeMedian.setProperty("value", 11)
        self.inShapeMedian.setObjectName(_fromUtf8("inShapeMedian"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(497, 114, 30, 30))
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setMaximumSize(QtCore.QSize(30, 30))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tiffImageLabel_16 = QtGui.QLabel(self.tab)
        self.tiffImageLabel_16.setGeometry(QtCore.QRect(9, 196, 146, 17))
        self.tiffImageLabel_16.setMinimumSize(QtCore.QSize(146, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel_16.setFont(font)
        self.tiffImageLabel_16.setObjectName(_fromUtf8("tiffImageLabel_16"))
        self.tiffImageLabel = QtGui.QLabel(self.tab)
        self.tiffImageLabel.setGeometry(QtCore.QRect(9, 32, 146, 17))
        self.tiffImageLabel.setMinimumSize(QtCore.QSize(146, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel.setFont(font)
        self.tiffImageLabel.setObjectName(_fromUtf8("tiffImageLabel"))
        self.selectRaster = QtGui.QPushButton(self.tab)
        self.selectRaster.setGeometry(QtCore.QRect(427, 191, 100, 25))
        self.selectRaster.setMinimumSize(QtCore.QSize(100, 25))
        self.selectRaster.setMaximumSize(QtCore.QSize(16777215, 25))
        self.selectRaster.setAutoDefault(False)
        self.selectRaster.setObjectName(_fromUtf8("selectRaster"))
        self.outRaster = QtGui.QLineEdit(self.tab)
        self.outRaster.setEnabled(True)
        self.outRaster.setGeometry(QtCore.QRect(161, 190, 251, 25))
        self.outRaster.setMinimumSize(QtCore.QSize(0, 25))
        self.outRaster.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.outRaster.setFont(font)
        self.outRaster.setText(_fromUtf8(""))
        self.outRaster.setObjectName(_fromUtf8("outRaster"))
        self.tiffImageLabel_13 = QtGui.QLabel(self.tab)
        self.tiffImageLabel_13.setGeometry(QtCore.QRect(312, 122, 68, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel_13.setFont(font)
        self.tiffImageLabel_13.setObjectName(_fromUtf8("tiffImageLabel_13"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(276, 78, 30, 30))
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(30, 30))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tiffImageLabel_2 = QtGui.QLabel(self.tab)
        self.tiffImageLabel_2.setGeometry(QtCore.QRect(9, 88, 148, 17))
        self.tiffImageLabel_2.setMinimumSize(QtCore.QSize(146, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel_2.setFont(font)
        self.tiffImageLabel_2.setToolTip(_fromUtf8(""))
        self.tiffImageLabel_2.setObjectName(_fromUtf8("tiffImageLabel_2"))
        self.inShapeGrey = gui.QgsSpinBox(self.tab)
        self.inShapeGrey.setGeometry(QtCore.QRect(167, 80, 99, 25))
        self.inShapeGrey.setMinimumSize(QtCore.QSize(83, 25))
        self.inShapeGrey.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.inShapeGrey.setFont(font)
        self.inShapeGrey.setMinimum(1)
        self.inShapeGrey.setMaximum(31)
        self.inShapeGrey.setSingleStep(2)
        self.inShapeGrey.setProperty("value", 11)
        self.inShapeGrey.setObjectName(_fromUtf8("inShapeGrey"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(276, 114, 30, 30))
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(30, 30))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.inRaster = gui.QgsMapLayerComboBox(self.tab)
        self.inRaster.setEnabled(True)
        self.inRaster.setGeometry(QtCore.QRect(161, 23, 366, 25))
        self.inRaster.setMinimumSize(QtCore.QSize(0, 25))
        self.inRaster.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.inRaster.setFont(font)
        self.inRaster.setFilters(gui.QgsMapLayerProxyModel.PluginLayer|gui.QgsMapLayerProxyModel.RasterLayer)
        self.inRaster.setObjectName(_fromUtf8("inRaster"))
        self.tiffImageLabel_3 = QtGui.QLabel(self.tab)
        self.tiffImageLabel_3.setGeometry(QtCore.QRect(9, 122, 151, 17))
        self.tiffImageLabel_3.setMinimumSize(QtCore.QSize(146, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel_3.setFont(font)
        self.tiffImageLabel_3.setObjectName(_fromUtf8("tiffImageLabel_3"))
        self.btnFilter = QtGui.QPushButton(self.tab)
        self.btnFilter.setGeometry(QtCore.QRect(372, 263, 150, 50))
        self.btnFilter.setMinimumSize(QtCore.QSize(150, 50))
        self.btnFilter.setMaximumSize(QtCore.QSize(120, 50))
        self.btnFilter.setAutoDefault(True)
        self.btnFilter.setDefault(False)
        self.btnFilter.setFlat(False)
        self.btnFilter.setObjectName(_fromUtf8("btnFilter"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(497, 40, 30, 30))
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setMaximumSize(QtCore.QSize(30, 30))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tiffImageLabel_10 = QtGui.QLabel(self.tab_2)
        self.tiffImageLabel_10.setGeometry(QtCore.QRect(9, 85, 76, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel_10.setFont(font)
        self.tiffImageLabel_10.setObjectName(_fromUtf8("tiffImageLabel_10"))
        self.tiffImageLabel_9 = QtGui.QLabel(self.tab_2)
        self.tiffImageLabel_9.setGeometry(QtCore.QRect(9, 122, 154, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel_9.setFont(font)
        self.tiffImageLabel_9.setObjectName(_fromUtf8("tiffImageLabel_9"))
        self.inClassifier = QtGui.QComboBox(self.tab_2)
        self.inClassifier.setGeometry(QtCore.QRect(169, 78, 140, 25))
        self.inClassifier.setMinimumSize(QtCore.QSize(0, 25))
        self.inClassifier.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.inClassifier.setFont(font)
        self.inClassifier.setObjectName(_fromUtf8("inClassifier"))
        self.inClassifier.addItem(_fromUtf8(""))
        self.inClassifier.addItem(_fromUtf8(""))
        self.inClassifier.addItem(_fromUtf8(""))
        self.inClassifier.addItem(_fromUtf8(""))
        self.outModel = QtGui.QLineEdit(self.tab_2)
        self.outModel.setGeometry(QtCore.QRect(169, 114, 176, 25))
        self.outModel.setMinimumSize(QtCore.QSize(0, 25))
        self.outModel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.outModel.setFont(font)
        self.outModel.setText(_fromUtf8(""))
        self.outModel.setObjectName(_fromUtf8("outModel"))
        self.selectModel = QtGui.QPushButton(self.tab_2)
        self.selectModel.setGeometry(QtCore.QRect(351, 114, 140, 25))
        self.selectModel.setMinimumSize(QtCore.QSize(0, 25))
        self.selectModel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.selectModel.setObjectName(_fromUtf8("selectModel"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(497, 112, 30, 30))
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setMaximumSize(QtCore.QSize(30, 30))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.tiffImageLabel_4 = QtGui.QLabel(self.tab_2)
        self.tiffImageLabel_4.setGeometry(QtCore.QRect(9, 13, 112, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel_4.setFont(font)
        self.tiffImageLabel_4.setObjectName(_fromUtf8("tiffImageLabel_4"))
        self.inFiltered = gui.QgsMapLayerComboBox(self.tab_2)
        self.inFiltered.setGeometry(QtCore.QRect(169, 9, 322, 25))
        self.inFiltered.setMinimumSize(QtCore.QSize(0, 25))
        self.inFiltered.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.inFiltered.setFont(font)
        self.inFiltered.setFilters(gui.QgsMapLayerProxyModel.PluginLayer|gui.QgsMapLayerProxyModel.RasterLayer)
        self.inFiltered.setObjectName(_fromUtf8("inFiltered"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(315, 76, 30, 30))
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setMaximumSize(QtCore.QSize(30, 30))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.tiffImageLabel_5 = QtGui.QLabel(self.tab_2)
        self.tiffImageLabel_5.setGeometry(QtCore.QRect(9, 48, 136, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel_5.setFont(font)
        self.tiffImageLabel_5.setObjectName(_fromUtf8("tiffImageLabel_5"))
        self.tiffImageLabel_17 = QtGui.QLabel(self.tab_2)
        self.tiffImageLabel_17.setGeometry(QtCore.QRect(9, 157, 130, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel_17.setFont(font)
        self.tiffImageLabel_17.setObjectName(_fromUtf8("tiffImageLabel_17"))
        self.outMatrix = QtGui.QLineEdit(self.tab_2)
        self.outMatrix.setGeometry(QtCore.QRect(169, 150, 176, 25))
        self.outMatrix.setMinimumSize(QtCore.QSize(0, 25))
        self.outMatrix.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.outMatrix.setFont(font)
        self.outMatrix.setObjectName(_fromUtf8("outMatrix"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(497, 148, 30, 30))
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(30, 30))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.selectMatrix = QtGui.QPushButton(self.tab_2)
        self.selectMatrix.setGeometry(QtCore.QRect(351, 150, 140, 25))
        self.selectMatrix.setMinimumSize(QtCore.QSize(0, 25))
        self.selectMatrix.setMaximumSize(QtCore.QSize(16777215, 25))
        self.selectMatrix.setObjectName(_fromUtf8("selectMatrix"))
        self.inTraining = gui.QgsMapLayerComboBox(self.tab_2)
        self.inTraining.setGeometry(QtCore.QRect(169, 42, 322, 25))
        self.inTraining.setMinimumSize(QtCore.QSize(0, 25))
        self.inTraining.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.inTraining.setFont(font)
        self.inTraining.setFilters(gui.QgsMapLayerProxyModel.HasGeometry|gui.QgsMapLayerProxyModel.LineLayer|gui.QgsMapLayerProxyModel.NoGeometry|gui.QgsMapLayerProxyModel.PluginLayer|gui.QgsMapLayerProxyModel.PointLayer|gui.QgsMapLayerProxyModel.PolygonLayer|gui.QgsMapLayerProxyModel.VectorLayer)
        self.inTraining.setObjectName(_fromUtf8("inTraining"))
        self.widget_2 = QtGui.QWidget(self.tab_2)
        self.widget_2.setGeometry(QtCore.QRect(9, 184, 341, 136))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.groupBox = QtGui.QGroupBox(self.widget_2)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 332, 118))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_23 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setMinimumSize(QtCore.QSize(20, 20))
        self.label_10.setMaximumSize(QtCore.QSize(20, 20))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_23.addWidget(self.label_10, 1, 2, 1, 1)
        self.inSeed = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.inSeed.setFont(font)
        self.inSeed.setDecimals(2)
        self.inSeed.setMaximum(1.0)
        self.inSeed.setSingleStep(0.01)
        self.inSeed.setProperty("value", 0.0)
        self.inSeed.setObjectName(_fromUtf8("inSeed"))
        self.gridLayout_23.addWidget(self.inSeed, 1, 1, 1, 1)
        self.inField = QtGui.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.inField.setFont(font)
        self.inField.setObjectName(_fromUtf8("inField"))
        self.inField.addItem(_fromUtf8(""))
        self.gridLayout_23.addWidget(self.inField, 0, 1, 1, 1)
        self.inSplit = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.inSplit.setFont(font)
        self.inSplit.setMaximum(1.0)
        self.inSplit.setSingleStep(0.01)
        self.inSplit.setProperty("value", 0.5)
        self.inSplit.setObjectName(_fromUtf8("inSplit"))
        self.gridLayout_23.addWidget(self.inSplit, 2, 1, 1, 1)
        self.tiffImageLabel_6 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.tiffImageLabel_6.setFont(font)
        self.tiffImageLabel_6.setObjectName(_fromUtf8("tiffImageLabel_6"))
        self.gridLayout_23.addWidget(self.tiffImageLabel_6, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setMinimumSize(QtCore.QSize(20, 20))
        self.label_11.setMaximumSize(QtCore.QSize(20, 20))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_23.addWidget(self.label_11, 2, 2, 1, 1)
        self.tiffImageLabel_8 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.tiffImageLabel_8.setFont(font)
        self.tiffImageLabel_8.setObjectName(_fromUtf8("tiffImageLabel_8"))
        self.gridLayout_23.addWidget(self.tiffImageLabel_8, 2, 0, 1, 1)
        self.tiffImageLabel_7 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.tiffImageLabel_7.setFont(font)
        self.tiffImageLabel_7.setObjectName(_fromUtf8("tiffImageLabel_7"))
        self.gridLayout_23.addWidget(self.tiffImageLabel_7, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setMinimumSize(QtCore.QSize(20, 20))
        self.label_9.setMaximumSize(QtCore.QSize(20, 20))
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_23.addWidget(self.label_9, 0, 2, 1, 1)
        self.btnTrain = QtGui.QPushButton(self.tab_2)
        self.btnTrain.setGeometry(QtCore.QRect(372, 263, 150, 50))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTrain.sizePolicy().hasHeightForWidth())
        self.btnTrain.setSizePolicy(sizePolicy)
        self.btnTrain.setMinimumSize(QtCore.QSize(150, 50))
        self.btnTrain.setMaximumSize(QtCore.QSize(120, 50))
        self.btnTrain.setBaseSize(QtCore.QSize(0, 0))
        self.btnTrain.setAutoFillBackground(False)
        self.btnTrain.setAutoDefault(True)
        self.btnTrain.setDefault(False)
        self.btnTrain.setFlat(False)
        self.btnTrain.setObjectName(_fromUtf8("btnTrain"))
        self.nFolds = QtGui.QSpinBox(self.tab_2)
        self.nFolds.setGeometry(QtCore.QRect(350, 79, 111, 27))
        self.nFolds.setProperty("value", 3)
        self.nFolds.setMaximum(999)
        self.nFolds.setMinimum(3)
        self.nFolds.setObjectName(_fromUtf8("nFolds"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.inFilteredStep3 = gui.QgsMapLayerComboBox(self.tab_3)
        self.inFilteredStep3.setGeometry(QtCore.QRect(142, 9, 345, 25))
        self.inFilteredStep3.setMinimumSize(QtCore.QSize(0, 25))
        self.inFilteredStep3.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.inFilteredStep3.setFont(font)
        self.inFilteredStep3.setFilters(gui.QgsMapLayerProxyModel.PluginLayer|gui.QgsMapLayerProxyModel.RasterLayer)
        self.inFilteredStep3.setObjectName(_fromUtf8("inFilteredStep3"))
        self.tiffImageLabel_19 = QtGui.QLabel(self.tab_3)
        self.tiffImageLabel_19.setGeometry(QtCore.QRect(9, 56, 102, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel_19.setFont(font)
        self.tiffImageLabel_19.setObjectName(_fromUtf8("tiffImageLabel_19"))
        self.inModel = QtGui.QLineEdit(self.tab_3)
        self.inModel.setGeometry(QtCore.QRect(142, 47, 251, 25))
        self.inModel.setMinimumSize(QtCore.QSize(0, 25))
        self.inModel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.inModel.setFont(font)
        self.inModel.setText(_fromUtf8(""))
        self.inModel.setObjectName(_fromUtf8("inModel"))
        self.tiffImageLabel_12 = QtGui.QLabel(self.tab_3)
        self.tiffImageLabel_12.setGeometry(QtCore.QRect(9, 16, 112, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel_12.setFont(font)
        self.tiffImageLabel_12.setObjectName(_fromUtf8("tiffImageLabel_12"))
        self.selectModelStep3 = QtGui.QPushButton(self.tab_3)
        self.selectModelStep3.setGeometry(QtCore.QRect(401, 46, 85, 27))
        self.selectModelStep3.setObjectName(_fromUtf8("selectModelStep3"))
        self.outShp = QtGui.QLineEdit(self.tab_3)
        self.outShp.setGeometry(QtCore.QRect(142, 85, 251, 25))
        self.outShp.setMinimumSize(QtCore.QSize(0, 25))
        self.outShp.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.outShp.setFont(font)
        self.outShp.setObjectName(_fromUtf8("outShp"))
        self.selectOutShp = QtGui.QPushButton(self.tab_3)
        self.selectOutShp.setGeometry(QtCore.QRect(401, 84, 85, 27))
        self.selectOutShp.setObjectName(_fromUtf8("selectOutShp"))
        self.tiffImageLabel_11 = QtGui.QLabel(self.tab_3)
        self.tiffImageLabel_11.setGeometry(QtCore.QRect(9, 93, 116, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tiffImageLabel_11.setFont(font)
        self.tiffImageLabel_11.setObjectName(_fromUtf8("tiffImageLabel_11"))
        self.btnClassify = QtGui.QPushButton(self.tab_3)
        self.btnClassify.setEnabled(True)
        self.btnClassify.setGeometry(QtCore.QRect(372, 263, 150, 50))
        self.btnClassify.setMinimumSize(QtCore.QSize(150, 50))
        self.btnClassify.setMaximumSize(QtCore.QSize(120, 50))
        self.btnClassify.setAutoDefault(True)
        self.btnClassify.setDefault(False)
        self.btnClassify.setObjectName(_fromUtf8("btnClassify"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 120, 491, 123))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.filterByArea = QtGui.QRadioButton(self.groupBox_2)
        self.filterByArea.setGeometry(QtCore.QRect(190, 25, 170, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filterByArea.setFont(font)
        self.filterByArea.setObjectName(_fromUtf8("filterByArea"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(330, 51, 30, 30))
        self.label_13.setMinimumSize(QtCore.QSize(0, 30))
        self.label_13.setMaximumSize(QtCore.QSize(30, 30))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tiffImageLabel_14 = QtGui.QLabel(self.groupBox_2)
        self.tiffImageLabel_14.setGeometry(QtCore.QRect(17, 51, 130, 27))
        self.tiffImageLabel_14.setMinimumSize(QtCore.QSize(130, 0))
        self.tiffImageLabel_14.setMaximumSize(QtCore.QSize(104, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tiffImageLabel_14.setFont(font)
        self.tiffImageLabel_14.setScaledContents(False)
        self.tiffImageLabel_14.setWordWrap(True)
        self.tiffImageLabel_14.setObjectName(_fromUtf8("tiffImageLabel_14"))
        self.filterByPixel = QtGui.QRadioButton(self.groupBox_2)
        self.filterByPixel.setGeometry(QtCore.QRect(17, 25, 167, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filterByPixel.setFont(font)
        self.filterByPixel.setChecked(True)
        self.filterByPixel.setObjectName(_fromUtf8("filterByPixel"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(330, 84, 30, 30))
        self.label_12.setMinimumSize(QtCore.QSize(0, 30))
        self.label_12.setMaximumSize(QtCore.QSize(30, 30))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.inMinSize = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.inMinSize.setGeometry(QtCore.QRect(190, 86, 97, 23))
        self.inMinSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inMinSize.setDecimals(0)
        self.inMinSize.setMaximum(1000.0)
        self.inMinSize.setSingleStep(1.0)
        self.inMinSize.setProperty("value", 10.0)
        self.inMinSize.setObjectName(_fromUtf8("inMinSize"))
        self.tiffImageLabel_18 = QtGui.QLabel(self.groupBox_2)
        self.tiffImageLabel_18.setGeometry(QtCore.QRect(17, 84, 167, 28))
        self.tiffImageLabel_18.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tiffImageLabel_18.setFont(font)
        self.tiffImageLabel_18.setScaledContents(False)
        self.tiffImageLabel_18.setWordWrap(True)
        self.tiffImageLabel_18.setObjectName(_fromUtf8("tiffImageLabel_18"))
        self.inClassForest = QtGui.QSpinBox(self.groupBox_2)
        self.inClassForest.setGeometry(QtCore.QRect(190, 53, 97, 23))
        self.inClassForest.setMinimumSize(QtCore.QSize(97, 0))
        self.inClassForest.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inClassForest.setMinimum(1)
        self.inClassForest.setProperty("value", 1)
        self.inClassForest.setObjectName(_fromUtf8("inClassForest"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.label_16 = QtGui.QLabel(HistoricalMap)
        self.label_16.setGeometry(QtCore.QRect(176, 480, 100, 35))
        self.label_16.setMinimumSize(QtCore.QSize(100, 35))
        self.label_16.setMaximumSize(QtCore.QSize(100, 35))
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/sigma.gif")))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(HistoricalMap)
        self.label_17.setGeometry(QtCore.QRect(389, 480, 160, 31))
        self.label_17.setMinimumSize(QtCore.QSize(160, 31))
        self.label_17.setMaximumSize(QtCore.QSize(160, 31))
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/ut2j.png")))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(HistoricalMap)
        self.label_18.setGeometry(QtCore.QRect(282, 480, 101, 31))
        self.label_18.setMinimumSize(QtCore.QSize(101, 31))
        self.label_18.setMaximumSize(QtCore.QSize(101, 31))
        self.label_18.setText(_fromUtf8(""))
        self.label_18.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/dynafor.gif")))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label = QtGui.QLabel(HistoricalMap)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(-1, 0, 570, 101))
        self.label.setMinimumSize(QtCore.QSize(450, 75))
        self.label.setMaximumSize(QtCore.QSize(900, 150))
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setLineWidth(0)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/historical_logo.jpg")))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_14 = QtGui.QLabel(HistoricalMap)
        self.label_14.setEnabled(True)
        self.label_14.setGeometry(QtCore.QRect(217, 500, 331, 29))
        self.label_14.setMinimumSize(QtCore.QSize(0, 29))
        self.label_14.setMaximumSize(QtCore.QSize(999, 999))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_14.setScaledContents(True)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_14.setOpenExternalLinks(True)
        self.label_14.setObjectName(_fromUtf8("label_14"))

        self.retranslateUi(HistoricalMap)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HistoricalMap)
        HistoricalMap.setTabOrder(self.inRaster, self.inShapeGrey)
        HistoricalMap.setTabOrder(self.inShapeGrey, self.inShapeMedian)
        HistoricalMap.setTabOrder(self.inShapeMedian, self.inShapeMedianIter)
        HistoricalMap.setTabOrder(self.inShapeMedianIter, self.outRaster)
        HistoricalMap.setTabOrder(self.outRaster, self.selectRaster)
        HistoricalMap.setTabOrder(self.selectRaster, self.btnFilter)
        HistoricalMap.setTabOrder(self.btnFilter, self.inFiltered)
        HistoricalMap.setTabOrder(self.inFiltered, self.inTraining)
        HistoricalMap.setTabOrder(self.inTraining, self.inClassifier)
        HistoricalMap.setTabOrder(self.inClassifier, self.outModel)
        HistoricalMap.setTabOrder(self.outModel, self.selectModel)
        HistoricalMap.setTabOrder(self.selectModel, self.outMatrix)
        HistoricalMap.setTabOrder(self.outMatrix, self.selectMatrix)
        HistoricalMap.setTabOrder(self.selectMatrix, self.inField)
        HistoricalMap.setTabOrder(self.inField, self.inSeed)
        HistoricalMap.setTabOrder(self.inSeed, self.inSplit)
        HistoricalMap.setTabOrder(self.inSplit, self.btnTrain)
        HistoricalMap.setTabOrder(self.btnTrain, self.inFilteredStep3)
        HistoricalMap.setTabOrder(self.inFilteredStep3, self.inModel)
        HistoricalMap.setTabOrder(self.inModel, self.selectModelStep3)
        HistoricalMap.setTabOrder(self.selectModelStep3, self.outShp)
        HistoricalMap.setTabOrder(self.outShp, self.selectOutShp)
        HistoricalMap.setTabOrder(self.selectOutShp, self.filterByPixel)
        HistoricalMap.setTabOrder(self.filterByPixel, self.filterByArea)
        HistoricalMap.setTabOrder(self.filterByArea, self.inClassForest)
        HistoricalMap.setTabOrder(self.inClassForest, self.inMinSize)
        HistoricalMap.setTabOrder(self.inMinSize, self.btnClassify)
        HistoricalMap.setTabOrder(self.btnClassify, self.tabWidget)

    def retranslateUi(self, HistoricalMap):
        HistoricalMap.setWindowTitle(_translate("HistoricalMap", "Historical Map - Automatic vectorizing old landcover", None))
        self.label_4.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>Number of iteration of the median filter. 3 means the script will perform 3 times the median filter.</p><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td><p><img src=\":/plugins/HistoricalMap/img/help/median1.png\"/></p></td><td><p><img src=\":/plugins/HistoricalMap/img/help/median5.png\"/></p></td></tr><tr><td><p>1 iteration</p></td><td><p>5 iterations</p></td></tr></table></body></html>", None))
        self.tiffImageLabel_16.setText(_translate("HistoricalMap", "Save result as :", None))
        self.tiffImageLabel.setText(_translate("HistoricalMap", "Image to filter :", None))
        self.selectRaster.setText(_translate("HistoricalMap", "...", None))
        self.outRaster.setPlaceholderText(_translate("HistoricalMap", "ex : map_filtered.tiff", None))
        self.tiffImageLabel_13.setText(_translate("HistoricalMap", "Iteration :", None))
        self.label_2.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>Closing filter is a max then a min filter. Here you can see the differences : </p><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td><p><img src=\":/plugins/HistoricalMap/img/help/original_sample.png\"/></p></td><td><p><img src=\":/plugins/HistoricalMap/img/help/grey5.png\"/></p></td><td><p><img src=\":/plugins/HistoricalMap/img/help/grey11.png\"/></p></td></tr><tr><td><p align=\"center\">Original</p></td><td><p align=\"center\">Size 5</p></td><td><p align=\"center\">Size 11</p></td></tr></table></body></html>", None))
        self.tiffImageLabel_2.setText(_translate("HistoricalMap", "Size of closing filter :", None))
        self.label_3.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>Median filter is used to remove noise and it perserves edges.<br/>Here you can see the differences after we use the closing filter with the same window size : </p><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td><p><img src=\":/plugins/HistoricalMap/img/help/original_sample.png\"/></p></td><td><p><img src=\":/plugins/HistoricalMap/img/help/gm5_5.png\"/></p></td><td><p><img src=\":/plugins/HistoricalMap/img/help/gm_11_11.png\"/></p></td></tr><tr><td><p align=\"center\">Original</p></td><td><p align=\"center\">Size 5</p></td><td><p align=\"center\">Size 11</p></td></tr></table></body></html>", None))
        self.tiffImageLabel_3.setText(_translate("HistoricalMap", "Size of median filter :", None))
        self.btnFilter.setText(_translate("HistoricalMap", "Filter", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("HistoricalMap", "Filter map (Step 1)", None))
        self.label_8.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>You need a SHP file with a column named \'Class\'.</p><p>In this column you have to make some polygons.</p><p>For example 1 is for Forest, 2 for Water.</p><p>Leave 0 for the script.</p></body></html>", None))
        self.tiffImageLabel_10.setText(_translate("HistoricalMap", "Classifier :", None))
        self.tiffImageLabel_9.setText(_translate("HistoricalMap", "Output Model name : ", None))
        self.inClassifier.setItemText(0, _translate("HistoricalMap", "GMM", None))
        self.inClassifier.setItemText(1, _translate("HistoricalMap", "KNN", None))
        self.inClassifier.setItemText(2, _translate("HistoricalMap", "RF", None))
        self.inClassifier.setItemText(3, _translate("HistoricalMap", "SVM", None))
        self.outModel.setPlaceholderText(_translate("HistoricalMap", "ex : modelGMM", None))
        self.selectModel.setText(_translate("HistoricalMap", "...", None))
        self.label_6.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>This will output the training model you will need for the step 3.</p><p>No extension.</p></body></html>", None))
        self.tiffImageLabel_4.setText(_translate("HistoricalMap", "Filtered image :", None))
        self.label_5.setToolTip(_translate("HistoricalMap", "GMM : Gaussian Mixture Model\n"
"KNN : K-Nearest Neighbors\n"
"RF : Random Forest\n"
"SVM : Support Vector Machine", None))
        self.tiffImageLabel_5.setText(_translate("HistoricalMap", "Training shapefile :", None))
        self.tiffImageLabel_17.setText(_translate("HistoricalMap", "Confusion matrix :", None))
        self.outMatrix.setPlaceholderText(_translate("HistoricalMap", "ex : matrixGMM.csv", None))
        self.label_7.setToolTip(_translate("HistoricalMap", "It will output a confusion matrix in a CSV format.", None))
        self.selectMatrix.setText(_translate("HistoricalMap", "...", None))
        self.groupBox.setTitle(_translate("HistoricalMap", "> Optional fields", None))
        self.label_10.setToolTip(_translate("HistoricalMap", "Default is 0. You can set the seed (or leave it to 0) to compare and have the same result.", None))
        self.inField.setItemText(0, _translate("HistoricalMap", "Class", None))
        self.tiffImageLabel_6.setText(_translate("HistoricalMap", "Seed : ", None))
        self.label_11.setToolTip(_translate("HistoricalMap", "Number (percent) of parcel that will be use for training.\n"
"For example 0,5 means that we use 50% of your parcel for making the model.", None))
        self.tiffImageLabel_8.setText(_translate("HistoricalMap", "Split : ", None))
        self.tiffImageLabel_7.setText(_translate("HistoricalMap", "Field column : ", None))
        self.label_9.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>By default you must have a column nammed \'Class\' where you put the id of your segmentation (1 for Forest, 2 for Water... You must leave 0 for the script). You can choose here your column.</p></body></html>", None))
        self.btnTrain.setText(_translate("HistoricalMap", "Train", None))
        self.nFolds.setSuffix(_translate("HistoricalMap", " folds", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("HistoricalMap", "Training (Step 2)", None))
        self.tiffImageLabel_19.setText(_translate("HistoricalMap", "Model name : ", None))
        self.inModel.setPlaceholderText(_translate("HistoricalMap", "ex : modelGMM", None))
        self.tiffImageLabel_12.setText(_translate("HistoricalMap", "Filtered image :", None))
        self.selectModelStep3.setText(_translate("HistoricalMap", "...", None))
        self.outShp.setPlaceholderText(_translate("HistoricalMap", "ex : Map_classified.shp", None))
        self.selectOutShp.setText(_translate("HistoricalMap", "...", None))
        self.tiffImageLabel_11.setText(_translate("HistoricalMap", "Save vector as :", None))
        self.btnClassify.setText(_translate("HistoricalMap", "Classify", None))
        self.groupBox_2.setTitle(_translate("HistoricalMap", "> Post treatment", None))
        self.filterByArea.setText(_translate("HistoricalMap", "Filter by area (slower)", None))
        self.label_13.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>The class you need to keep. For example if the old forest is class 1, let 1 in the field.</p></body></html>", None))
        self.tiffImageLabel_14.setText(_translate("HistoricalMap", "Class number :", None))
        self.filterByPixel.setText(_translate("HistoricalMap", "Filter by pixel (faster)", None))
        self.label_12.setToolTip(_translate("HistoricalMap", "<html><head/><body><p><span style=\" font-weight:600;\">filter by pixel</span></p><p>remove raster polygons by a sieve in pixel (diagonal pixels are not considered directly connected).</p><p><span style=\" font-weight:600;\">filter by area</span></p><p>keep default system divised by 100. If you use Lambert III (EPSG 2154), 0,5 means 0,5 hectares (5000m2). We usually consider a forest is at least 0,5 ha, so you can remove all polygons below a certain size, by default 0,5 acre.</p></body></html>", None))
        self.inMinSize.setSuffix(_translate("HistoricalMap", " pixels", None))
        self.tiffImageLabel_18.setText(_translate("HistoricalMap", "Min parcel size :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("HistoricalMap", "Classify (Step 3)", None))
        self.label_14.setToolTip(_translate("HistoricalMap", "Go to our online wiki", None))
        self.label_14.setText(_translate("HistoricalMap", "<html><head/><body><p>Need help ? You can consult our <a href=\"https://github.com/lennepkade/HistoricalMap/wiki\"><span style=\" text-decoration: underline; color:#0000ff;\">online wiki</span></a> or our <a href=\"https://github.com/lennepkade/HistoricalMap\"><span style=\" text-decoration: underline; color:#0000ff;\">github page</span></a>.</p></body></html>", None))

from qgis import gui
