# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historical_map_dialog_base.ui'
#
# Created: Fri Feb 12 20:50:46 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HistoricalMap(object):
    def setupUi(self, HistoricalMap):
        
        HistoricalMap.setObjectName(_fromUtf8("HistoricalMap"))
        HistoricalMap.resize(590, 588)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(74)
        sizePolicy.setVerticalStretch(74)
        sizePolicy.setHeightForWidth(HistoricalMap.sizePolicy().hasHeightForWidth())
        HistoricalMap.setSizePolicy(sizePolicy)
        HistoricalMap.setMinimumSize(QtCore.QSize(590, 588))
        HistoricalMap.setMaximumSize(QtCore.QSize(590, 588))
        self.tabWidget = QtGui.QTabWidget(HistoricalMap)
        self.tabWidget.setGeometry(QtCore.QRect(10, 200, 569, 381))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAccessibleDescription(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tiffImageLabel_3 = QtGui.QLabel(self.tab)
        self.tiffImageLabel_3.setGeometry(QtCore.QRect(9, 170, 201, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel_3.setFont(font)
        self.tiffImageLabel_3.setObjectName(_fromUtf8("tiffImageLabel_3"))
        self.inRaster = gui.QgsMapLayerComboBox(self.tab)
        self.inRaster.setGeometry(QtCore.QRect(190, 40, 361, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inRaster.setFont(font)
        self.inRaster.setFilters(gui.QgsMapLayerProxyModel.PluginLayer|gui.QgsMapLayerProxyModel.RasterLayer)
        self.inRaster.setObjectName(_fromUtf8("inRaster"))
        self.tiffImageLabel = QtGui.QLabel(self.tab)
        self.tiffImageLabel.setGeometry(QtCore.QRect(9, 40, 141, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel.setFont(font)
        self.tiffImageLabel.setObjectName(_fromUtf8("tiffImageLabel"))
        self.tiffImageLabel_16 = QtGui.QLabel(self.tab)
        self.tiffImageLabel_16.setGeometry(QtCore.QRect(9, 240, 161, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel_16.setFont(font)
        self.tiffImageLabel_16.setObjectName(_fromUtf8("tiffImageLabel_16"))
        self.tiffImageLabel_2 = QtGui.QLabel(self.tab)
        self.tiffImageLabel_2.setGeometry(QtCore.QRect(9, 100, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel_2.setFont(font)
        self.tiffImageLabel_2.setObjectName(_fromUtf8("tiffImageLabel_2"))
        self.outRaster = QtGui.QLineEdit(self.tab)
        self.outRaster.setGeometry(QtCore.QRect(190, 240, 201, 30))
        self.outRaster.setText(_fromUtf8(""))
        self.outRaster.setObjectName(_fromUtf8("outRaster"))
        self.selectRaster = QtGui.QPushButton(self.tab)
        self.selectRaster.setGeometry(QtCore.QRect(400, 240, 151, 30))
        self.selectRaster.setMinimumSize(QtCore.QSize(100, 0))
        self.selectRaster.setAutoDefault(False)
        self.selectRaster.setObjectName(_fromUtf8("selectRaster"))
        self.inShapeGrey = gui.QgsSpinBox(self.tab)
        self.inShapeGrey.setGeometry(QtCore.QRect(190, 100, 98, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inShapeGrey.setFont(font)
        self.inShapeGrey.setMinimum(1)
        self.inShapeGrey.setMaximum(31)
        self.inShapeGrey.setSingleStep(2)
        self.inShapeGrey.setProperty("value", 11)
        self.inShapeGrey.setObjectName(_fromUtf8("inShapeGrey"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(300, 100, 30, 30))
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(30, 30))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(300, 165, 30, 30))
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(30, 30))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.inShapeMedianIter = gui.QgsSpinBox(self.tab)
        self.inShapeMedianIter.setGeometry(QtCore.QRect(430, 170, 80, 25))
        self.inShapeMedianIter.setMinimumSize(QtCore.QSize(60, 25))
        self.inShapeMedianIter.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inShapeMedianIter.setFont(font)
        self.inShapeMedianIter.setMinimum(1)
        self.inShapeMedianIter.setMaximum(50)
        self.inShapeMedianIter.setSingleStep(1)
        self.inShapeMedianIter.setProperty("value", 1)
        self.inShapeMedianIter.setObjectName(_fromUtf8("inShapeMedianIter"))
        self.tiffImageLabel_13 = QtGui.QLabel(self.tab)
        self.tiffImageLabel_13.setGeometry(QtCore.QRect(340, 170, 83, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel_13.setFont(font)
        self.tiffImageLabel_13.setObjectName(_fromUtf8("tiffImageLabel_13"))
        self.inShapeMedian = gui.QgsSpinBox(self.tab)
        self.inShapeMedian.setGeometry(QtCore.QRect(190, 170, 98, 25))
        self.inShapeMedian.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inShapeMedian.setFont(font)
        self.inShapeMedian.setMinimum(1)
        self.inShapeMedian.setMaximum(31)
        self.inShapeMedian.setSingleStep(2)
        self.inShapeMedian.setProperty("value", 11)
        self.inShapeMedian.setObjectName(_fromUtf8("inShapeMedian"))
        self.btnFilter = QtGui.QPushButton(self.tab)
        self.btnFilter.setGeometry(QtCore.QRect(400, 280, 150, 50))
        self.btnFilter.setMinimumSize(QtCore.QSize(150, 50))
        self.btnFilter.setAutoDefault(True)
        self.btnFilter.setDefault(False)
        self.btnFilter.setFlat(False)
        self.btnFilter.setObjectName(_fromUtf8("btnFilter"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(520, 165, 30, 30))
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setMaximumSize(QtCore.QSize(30, 30))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tiffImageLabel_4 = QtGui.QLabel(self.tab_2)
        self.tiffImageLabel_4.setGeometry(QtCore.QRect(9, 18, 132, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel_4.setFont(font)
        self.tiffImageLabel_4.setObjectName(_fromUtf8("tiffImageLabel_4"))
        self.inFiltered = gui.QgsMapLayerComboBox(self.tab_2)
        self.inFiltered.setGeometry(QtCore.QRect(208, 12, 341, 30))
        self.inFiltered.setFilters(gui.QgsMapLayerProxyModel.PluginLayer|gui.QgsMapLayerProxyModel.RasterLayer)
        self.inFiltered.setObjectName(_fromUtf8("inFiltered"))
        self.tiffImageLabel_5 = QtGui.QLabel(self.tab_2)
        self.tiffImageLabel_5.setGeometry(QtCore.QRect(9, 53, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel_5.setFont(font)
        self.tiffImageLabel_5.setObjectName(_fromUtf8("tiffImageLabel_5"))
        self.inTraining = gui.QgsMapLayerComboBox(self.tab_2)
        self.inTraining.setGeometry(QtCore.QRect(208, 48, 295, 30))
        self.inTraining.setFilters(gui.QgsMapLayerProxyModel.HasGeometry|gui.QgsMapLayerProxyModel.LineLayer|gui.QgsMapLayerProxyModel.NoGeometry|gui.QgsMapLayerProxyModel.PluginLayer|gui.QgsMapLayerProxyModel.PointLayer|gui.QgsMapLayerProxyModel.PolygonLayer|gui.QgsMapLayerProxyModel.VectorLayer)
        self.inTraining.setObjectName(_fromUtf8("inTraining"))
        self.tiffImageLabel_10 = QtGui.QLabel(self.tab_2)
        self.tiffImageLabel_10.setGeometry(QtCore.QRect(9, 90, 87, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel_10.setFont(font)
        self.tiffImageLabel_10.setObjectName(_fromUtf8("tiffImageLabel_10"))
        self.inClassifier = QtGui.QComboBox(self.tab_2)
        self.inClassifier.setGeometry(QtCore.QRect(208, 82, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inClassifier.setFont(font)
        self.inClassifier.setObjectName(_fromUtf8("inClassifier"))
        self.inClassifier.addItem(_fromUtf8(""))
        self.inClassifier.addItem(_fromUtf8(""))
        self.inClassifier.addItem(_fromUtf8(""))
        self.inClassifier.addItem(_fromUtf8(""))
        self.tiffImageLabel_9 = QtGui.QLabel(self.tab_2)
        self.tiffImageLabel_9.setGeometry(QtCore.QRect(9, 125, 185, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel_9.setFont(font)
        self.tiffImageLabel_9.setObjectName(_fromUtf8("tiffImageLabel_9"))
        self.outModel = QtGui.QLineEdit(self.tab_2)
        self.outModel.setGeometry(QtCore.QRect(208, 120, 201, 30))
        self.outModel.setText(_fromUtf8(""))
        self.outModel.setObjectName(_fromUtf8("outModel"))
        self.selectModel = QtGui.QPushButton(self.tab_2)
        self.selectModel.setGeometry(QtCore.QRect(420, 120, 85, 30))
        self.selectModel.setObjectName(_fromUtf8("selectModel"))
        self.tiffImageLabel_17 = QtGui.QLabel(self.tab_2)
        self.tiffImageLabel_17.setGeometry(QtCore.QRect(9, 164, 154, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel_17.setFont(font)
        self.tiffImageLabel_17.setObjectName(_fromUtf8("tiffImageLabel_17"))
        self.outMatrix = QtGui.QLineEdit(self.tab_2)
        self.outMatrix.setGeometry(QtCore.QRect(208, 160, 201, 30))
        self.outMatrix.setObjectName(_fromUtf8("outMatrix"))
        self.selectMatrix = QtGui.QPushButton(self.tab_2)
        self.selectMatrix.setGeometry(QtCore.QRect(420, 160, 85, 30))
        self.selectMatrix.setObjectName(_fromUtf8("selectMatrix"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 210, 311, 129))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setMinimumSize(QtCore.QSize(0, 30))
        self.label_11.setMaximumSize(QtCore.QSize(30, 30))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 2, 2, 1, 1)
        self.tiffImageLabel_7 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tiffImageLabel_7.setFont(font)
        self.tiffImageLabel_7.setObjectName(_fromUtf8("tiffImageLabel_7"))
        self.gridLayout_4.addWidget(self.tiffImageLabel_7, 0, 0, 1, 1)
        self.tiffImageLabel_8 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tiffImageLabel_8.setFont(font)
        self.tiffImageLabel_8.setObjectName(_fromUtf8("tiffImageLabel_8"))
        self.gridLayout_4.addWidget(self.tiffImageLabel_8, 2, 0, 1, 1)
        self.inSplit = QtGui.QDoubleSpinBox(self.groupBox)
        self.inSplit.setMaximum(1.0)
        self.inSplit.setSingleStep(0.01)
        self.inSplit.setProperty("value", 0.5)
        self.inSplit.setObjectName(_fromUtf8("inSplit"))
        self.gridLayout_4.addWidget(self.inSplit, 2, 1, 1, 1)
        self.inSeed = QtGui.QDoubleSpinBox(self.groupBox)
        self.inSeed.setDecimals(2)
        self.inSeed.setMaximum(1.0)
        self.inSeed.setSingleStep(0.01)
        self.inSeed.setProperty("value", 0.0)
        self.inSeed.setObjectName(_fromUtf8("inSeed"))
        self.gridLayout_4.addWidget(self.inSeed, 1, 1, 1, 1)
        self.tiffImageLabel_6 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tiffImageLabel_6.setFont(font)
        self.tiffImageLabel_6.setObjectName(_fromUtf8("tiffImageLabel_6"))
        self.gridLayout_4.addWidget(self.tiffImageLabel_6, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setMaximumSize(QtCore.QSize(30, 30))
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.label_10.setMaximumSize(QtCore.QSize(30, 30))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 1, 2, 1, 1)
        self.inField = QtGui.QComboBox(self.groupBox)
        self.inField.setObjectName(_fromUtf8("inField"))
        self.inField.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.inField, 0, 1, 1, 1)
        self.btnTrain = QtGui.QPushButton(self.tab_2)
        self.btnTrain.setGeometry(QtCore.QRect(400, 280, 150, 50))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTrain.sizePolicy().hasHeightForWidth())
        self.btnTrain.setSizePolicy(sizePolicy)
        self.btnTrain.setMinimumSize(QtCore.QSize(150, 50))
        self.btnTrain.setBaseSize(QtCore.QSize(0, 0))
        self.btnTrain.setAutoFillBackground(False)
        self.btnTrain.setAutoDefault(True)
        self.btnTrain.setDefault(False)
        self.btnTrain.setFlat(False)
        self.btnTrain.setObjectName(_fromUtf8("btnTrain"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(310, 83, 30, 30))
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setMaximumSize(QtCore.QSize(30, 30))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(510, 116, 30, 30))
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setMaximumSize(QtCore.QSize(30, 30))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(510, 156, 30, 30))
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(30, 30))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(510, 46, 30, 30))
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setMaximumSize(QtCore.QSize(30, 30))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.inModel = QtGui.QLineEdit(self.tab_3)
        self.inModel.setGeometry(QtCore.QRect(162, 72, 291, 30))
        self.inModel.setText(_fromUtf8(""))
        self.inModel.setObjectName(_fromUtf8("inModel"))
        self.inFilteredStep3 = gui.QgsMapLayerComboBox(self.tab_3)
        self.inFilteredStep3.setGeometry(QtCore.QRect(162, 20, 388, 30))
        self.inFilteredStep3.setFilters(gui.QgsMapLayerProxyModel.PluginLayer|gui.QgsMapLayerProxyModel.RasterLayer)
        self.inFilteredStep3.setObjectName(_fromUtf8("inFilteredStep3"))
        self.selectOutShp = QtGui.QPushButton(self.tab_3)
        self.selectOutShp.setGeometry(QtCore.QRect(470, 130, 80, 30))
        self.selectOutShp.setObjectName(_fromUtf8("selectOutShp"))
        self.tiffImageLabel_12 = QtGui.QLabel(self.tab_3)
        self.tiffImageLabel_12.setGeometry(QtCore.QRect(9, 30, 132, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel_12.setFont(font)
        self.tiffImageLabel_12.setObjectName(_fromUtf8("tiffImageLabel_12"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 190, 541, 131))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(0, 30, 521, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(220, 50, 30, 30))
        self.label_13.setMinimumSize(QtCore.QSize(0, 30))
        self.label_13.setMaximumSize(QtCore.QSize(30, 30))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tiffImageLabel_18 = QtGui.QLabel(self.groupBox_2)
        self.tiffImageLabel_18.setGeometry(QtCore.QRect(7, 95, 181, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tiffImageLabel_18.setFont(font)
        self.tiffImageLabel_18.setObjectName(_fromUtf8("tiffImageLabel_18"))
        self.tiffImageLabel_14 = QtGui.QLabel(self.groupBox_2)
        self.tiffImageLabel_14.setGeometry(QtCore.QRect(9, 55, 122, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tiffImageLabel_14.setFont(font)
        self.tiffImageLabel_14.setObjectName(_fromUtf8("tiffImageLabel_14"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(220, 90, 30, 30))
        self.label_12.setMinimumSize(QtCore.QSize(0, 30))
        self.label_12.setMaximumSize(QtCore.QSize(30, 30))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/help/information.png")))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.inMinSize = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.inMinSize.setGeometry(QtCore.QRect(120, 90, 91, 27))
        self.inMinSize.setDecimals(1)
        self.inMinSize.setSingleStep(0.1)
        self.inMinSize.setProperty("value", 0.5)
        self.inMinSize.setObjectName(_fromUtf8("inMinSize"))
        self.inClassForest = QtGui.QSpinBox(self.groupBox_2)
        self.inClassForest.setGeometry(QtCore.QRect(120, 50, 91, 27))
        self.inClassForest.setMinimum(1)
        self.inClassForest.setProperty("value", 1)
        self.inClassForest.setObjectName(_fromUtf8("inClassForest"))
        self.tiffImageLabel_11 = QtGui.QLabel(self.tab_3)
        self.tiffImageLabel_11.setGeometry(QtCore.QRect(9, 135, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel_11.setFont(font)
        self.tiffImageLabel_11.setObjectName(_fromUtf8("tiffImageLabel_11"))
        self.tiffImageLabel_19 = QtGui.QLabel(self.tab_3)
        self.tiffImageLabel_19.setGeometry(QtCore.QRect(9, 80, 119, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tiffImageLabel_19.setFont(font)
        self.tiffImageLabel_19.setObjectName(_fromUtf8("tiffImageLabel_19"))
        self.outShp = QtGui.QLineEdit(self.tab_3)
        self.outShp.setGeometry(QtCore.QRect(162, 130, 291, 30))
        self.outShp.setObjectName(_fromUtf8("outShp"))
        self.selectModelStep3 = QtGui.QPushButton(self.tab_3)
        self.selectModelStep3.setGeometry(QtCore.QRect(470, 72, 80, 30))
        self.selectModelStep3.setObjectName(_fromUtf8("selectModelStep3"))
        self.btnClassify = QtGui.QPushButton(self.tab_3)
        self.btnClassify.setGeometry(QtCore.QRect(400, 280, 150, 50))
        self.btnClassify.setMinimumSize(QtCore.QSize(150, 50))
        self.btnClassify.setAutoDefault(True)
        self.btnClassify.setDefault(False)
        self.btnClassify.setObjectName(_fromUtf8("btnClassify"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.label = QtGui.QLabel(HistoricalMap)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 601, 191))
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setLineWidth(0)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/HistoricalMap/img/historical_logo.jpg")))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(HistoricalMap)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HistoricalMap)
        HistoricalMap.setTabOrder(self.inRaster, self.inShapeGrey)
        HistoricalMap.setTabOrder(self.inShapeGrey, self.inShapeMedian)
        HistoricalMap.setTabOrder(self.inShapeMedian, self.inShapeMedianIter)
        HistoricalMap.setTabOrder(self.inShapeMedianIter, self.outRaster)
        HistoricalMap.setTabOrder(self.outRaster, self.selectRaster)
        HistoricalMap.setTabOrder(self.selectRaster, self.btnFilter)
        HistoricalMap.setTabOrder(self.btnFilter, self.inFiltered)
        HistoricalMap.setTabOrder(self.inFiltered, self.inTraining)
        HistoricalMap.setTabOrder(self.inTraining, self.inClassifier)
        HistoricalMap.setTabOrder(self.inClassifier, self.outModel)
        HistoricalMap.setTabOrder(self.outModel, self.selectModel)
        HistoricalMap.setTabOrder(self.selectModel, self.outMatrix)
        HistoricalMap.setTabOrder(self.outMatrix, self.selectMatrix)
        HistoricalMap.setTabOrder(self.selectMatrix, self.inField)
        HistoricalMap.setTabOrder(self.inField, self.inSeed)
        HistoricalMap.setTabOrder(self.inSeed, self.inSplit)
        HistoricalMap.setTabOrder(self.inSplit, self.btnTrain)
        HistoricalMap.setTabOrder(self.btnTrain, self.inFilteredStep3)
        HistoricalMap.setTabOrder(self.inFilteredStep3, self.inModel)
        HistoricalMap.setTabOrder(self.inModel, self.selectModelStep3)
        HistoricalMap.setTabOrder(self.selectModelStep3, self.outShp)
        HistoricalMap.setTabOrder(self.outShp, self.selectOutShp)
        HistoricalMap.setTabOrder(self.selectOutShp, self.inClassForest)
        HistoricalMap.setTabOrder(self.inClassForest, self.inMinSize)
        HistoricalMap.setTabOrder(self.inMinSize, self.btnClassify)
        HistoricalMap.setTabOrder(self.btnClassify, self.tabWidget)

    def retranslateUi(self, HistoricalMap):
        HistoricalMap.setWindowTitle(_translate("HistoricalMap", "Historical Map - Automatic vectorizing old landcover", None))
        self.tiffImageLabel_3.setText(_translate("HistoricalMap", "Size of median filter :", None))
        self.tiffImageLabel.setText(_translate("HistoricalMap", "Image to filter :", None))
        self.tiffImageLabel_16.setText(_translate("HistoricalMap", "Save result as :", None))
        self.tiffImageLabel_2.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>Closing filter is a max then a min filter. Here you can see the difference between size 5 or 11 :</p><p><img src=\"img/grey5.png\" width=\"131\" height=\"65\"/><img src=\"img/grey11.png\" width=\"131\" height=\"65\"/></p></body></html>", None))
        self.tiffImageLabel_2.setText(_translate("HistoricalMap", "Size of closing filter :", None))
        self.outRaster.setPlaceholderText(_translate("HistoricalMap", "ex : map_filtered.tiff", None))
        self.selectRaster.setText(_translate("HistoricalMap", "...", None))
        self.label_2.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>Closing filter is a max then a min filter. Here you can see the differences : </p><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td><p><img src=\":/plugins/HistoricalMap/img/help/original_sample.png\"/></p></td><td><p><img src=\":/plugins/HistoricalMap/img/help/grey5.png\"/></p></td><td><p><img src=\":/plugins/HistoricalMap/img/help/grey11.png\"/></p></td></tr><tr><td><p align=\"center\">Original</p></td><td><p align=\"center\">Size 5</p></td><td><p align=\"center\">Size 11</p></td></tr></table></body></html>", None))
        self.label_3.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>Median filter is used to remove noise and it perserves edges.<br/>Here you can see the differences after we use the closing filter with the same window size : </p><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td><p><img src=\":/plugins/HistoricalMap/img/help/original_sample.png\"/></p></td><td><p><img src=\":/plugins/HistoricalMap/img/help/gm5_5.png\"/></p></td><td><p><img src=\":/plugins/HistoricalMap/img/help/gm_11_11.png\"/></p></td></tr><tr><td><p align=\"center\">Original</p></td><td><p align=\"center\">Size 5</p></td><td><p align=\"center\">Size 11</p></td></tr></table></body></html>", None))
        self.tiffImageLabel_13.setText(_translate("HistoricalMap", "Iteration :", None))
        self.btnFilter.setText(_translate("HistoricalMap", "Filter", None))
        self.label_4.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>Number of iteration of the median filter. 3 means the script will perform 3 times the median filter.</p><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td><p><img src=\":/plugins/HistoricalMap/img/help/median1.png\"/></p></td><td><p><img src=\":/plugins/HistoricalMap/img/help/median5.png\"/></p></td></tr><tr><td><p>1 iteration</p></td><td><p>5 iterations</p></td></tr></table></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("HistoricalMap", "Filter map (Step 1)", None))
        self.tiffImageLabel_4.setText(_translate("HistoricalMap", "Filtered image :", None))
        self.tiffImageLabel_5.setText(_translate("HistoricalMap", "Training shapefile :", None))
        self.tiffImageLabel_10.setText(_translate("HistoricalMap", "Classifier :", None))
        self.inClassifier.setItemText(0, _translate("HistoricalMap", "GMM", None))
        self.inClassifier.setItemText(1, _translate("HistoricalMap", "KNN", None))
        self.inClassifier.setItemText(2, _translate("HistoricalMap", "RF", None))
        self.inClassifier.setItemText(3, _translate("HistoricalMap", "SVM", None))
        self.tiffImageLabel_9.setText(_translate("HistoricalMap", "Output Model name : ", None))
        self.outModel.setPlaceholderText(_translate("HistoricalMap", "ex : modelGMM", None))
        self.selectModel.setText(_translate("HistoricalMap", "...", None))
        self.tiffImageLabel_17.setText(_translate("HistoricalMap", "Confusion matrix :", None))
        self.outMatrix.setPlaceholderText(_translate("HistoricalMap", "ex : matrixGMM.csv", None))
        self.selectMatrix.setText(_translate("HistoricalMap", "...", None))
        self.groupBox.setTitle(_translate("HistoricalMap", "> Optional fields", None))
        self.label_11.setToolTip(_translate("HistoricalMap", "Number (percent) of parcel that will be use for training.\n"
"For example 0,5 means that we use 50% of your parcel for making the model.", None))
        self.tiffImageLabel_7.setText(_translate("HistoricalMap", "Field column : ", None))
        self.tiffImageLabel_8.setText(_translate("HistoricalMap", "Split : ", None))
        self.tiffImageLabel_6.setText(_translate("HistoricalMap", "Seed : ", None))
        self.label_9.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>By default you must have a column nammed \'Class\' where you put the id of your segmentation (1 for Forest, 2 for Water... You must leave 0 for the script). You can choose here your column.</p></body></html>", None))
        self.label_10.setToolTip(_translate("HistoricalMap", "Default is 0. You can set the seed (or leave it to 0) to compare and have the same result.", None))
        self.inField.setItemText(0, _translate("HistoricalMap", "Class", None))
        self.btnTrain.setText(_translate("HistoricalMap", "Train", None))
        self.label_5.setToolTip(_translate("HistoricalMap", "GMM : Gaussian Mixture Model\n"
"KNN : K-Nearest Neighbors\n"
"RF : Random Forest\n"
"SVM : Support Vector Machine", None))
        self.label_6.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>This will output the training model you will need for the step 3.</p><p>No extension.</p></body></html>", None))
        self.label_7.setToolTip(_translate("HistoricalMap", "It will output a confusion matrix in a CSV format.", None))
        self.label_8.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>You need a SHP file with a column named \'Class\'.</p><p>In this column you have to make some polygons.</p><p>For example 1 is for Forest, 2 for Water.</p><p>Leave 0 for the script.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("HistoricalMap", "Training (Step 2)", None))
        self.inModel.setPlaceholderText(_translate("HistoricalMap", "ex : modelGMM", None))
        self.selectOutShp.setText(_translate("HistoricalMap", "...", None))
        self.tiffImageLabel_12.setText(_translate("HistoricalMap", "Filtered image :", None))
        self.groupBox_2.setTitle(_translate("HistoricalMap", "> Optional fields", None))
        self.label_14.setText(_translate("HistoricalMap", "<html><head/><body><p>Classification number of the forest is by default 1, and the minimum size of the forest is set to 0,5 hectare.</p></body></html>", None))
        self.label_13.setToolTip(_translate("HistoricalMap", "<html><head/><body><p>By default you must have a column named \'Class\' where you put the id of your segmentation (1 for Forest, 2 for Water... You must leave 0 for the script).</p><p>We consider 1 as the forest to make the classification.</p></body></html>", None))
        self.tiffImageLabel_18.setText(_translate("HistoricalMap", "Min parcel size :", None))
        self.tiffImageLabel_14.setText(_translate("HistoricalMap", "Class number :", None))
        self.label_12.setToolTip(_translate("HistoricalMap", "Default system divised by 100. If you use Lambert III (EPSG 2154),  0,5 means 0,5 acre (0,5 hectares, or 5000m2). We usually consider a forest is at least 0,5 acre, so you can remove all polygons below a certain size, by default 0,5 acre.", None))
        self.tiffImageLabel_11.setText(_translate("HistoricalMap", "Save vector as :", None))
        self.tiffImageLabel_19.setText(_translate("HistoricalMap", "Model name : ", None))
        self.outShp.setPlaceholderText(_translate("HistoricalMap", "ex : Map_classified.shp", None))
        self.selectModelStep3.setText(_translate("HistoricalMap", "...", None))
        self.btnClassify.setText(_translate("HistoricalMap", "Classify", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("HistoricalMap", "Classify (Step 3)", None))

from qgis import gui
